export const activityColors = [
  {
    // type: 'Outdoor Adventure',
    badge: 'bg-emerald-500',
    icon: 'text-emerald-500',
    button: 'bg-emerald-500 hover:bg-emerald-600',
    ageBadgeLight: 'bg-emerald-100 text-emerald-700',
    ageBadgeDark: 'bg-emerald-900 text-emerald-300',
  },
  {
    // type: 'Educational Workshop',
    badge: 'bg-sky-500',
    icon: 'text-sky-500',
    button: 'bg-sky-500 hover:bg-sky-600',
    ageBadgeLight: 'bg-sky-100 text-sky-700',
    ageBadgeDark: 'bg-sky-900 text-sky-300',
  },
  {
    // type: 'Sports & Fitness',
    badge: 'bg-amber-500',
    icon: 'text-amber-500',
    button: 'bg-amber-500 hover:bg-amber-600',
    ageBadgeLight: 'bg-amber-100 text-amber-700',
    ageBadgeDark: 'bg-amber-900 text-amber-300',
  },
  {
    // type: 'Arts & Culture',
    badge: 'bg-violet-500',
    icon: 'text-violet-500',
    button: 'bg-violet-500 hover:bg-violet-600',
    ageBadgeLight: 'bg-violet-100 text-violet-700',
    ageBadgeDark: 'bg-violet-900 text-violet-300',
  },
  {
    // type: 'Tech & Innovation',
    badge: 'bg-rose-500',
    icon: 'text-rose-500',
    button: 'bg-rose-500 hover:bg-rose-600',
    ageBadgeLight: 'bg-rose-100 text-rose-700',
    ageBadgeDark: 'bg-rose-900 text-rose-300',
  },
  {
    // type: 'Social Gathering',
    badge: 'bg-cyan-500',
    icon: 'text-cyan-500',
    button: 'bg-cyan-500 hover:bg-cyan-600',
    ageBadgeLight: 'bg-cyan-100 text-cyan-700',
    ageBadgeDark: 'bg-cyan-900 text-cyan-300',
  },
];
